# Generated by Django 2.0.9 on 2019-03-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_auto_20190311_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='consumType',
            field=models.IntegerField(default=0),
        ),
    ]
