# Generated by Django 2.0.9 on 2019-03-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_income_consumtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='consumType',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
