# Generated by Django 2.0.9 on 2019-03-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0007_salarydata_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydata',
            name='endHour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salarydata',
            name='isSetData',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salarydata',
            name='monthSallery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salarydata',
            name='salaryDay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salarydata',
            name='salaryPayType',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salarydata',
            name='selectWeek',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarydata',
            name='standardMonth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salarydata',
            name='startHour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salarydata',
            name='workingHour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salarydata',
            name='workingWeekDay',
            field=models.IntegerField(default=0),
        ),
    ]
