# Generated by Django 2.0.9 on 2019-03-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0008_auto_20190314_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarydata',
            name='salaryPayType',
            field=models.CharField(max_length=50),
        ),
    ]
