# Generated by Django 2.0.9 on 2019-03-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0010_remove_salarydata_standardmonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarydata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
