# Generated by Django 2.0.9 on 2019-03-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20181018_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='image',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='to',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('today', 'Today Complete'), ('month', 'Month Complete'), ('holi', 'Today Holiday')], max_length=20),
        ),
    ]
